# Generated by Django 6.0.3 on 2026-04-04 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='last_intent',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='last_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product'),
        ),
    ]
