# Generated by Django 6.0.3 on 2026-04-04 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_lead_last_intent_lead_last_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='last_intent',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='last_product',
        ),
    ]
