# Generated by Django 6.0.3 on 2026-04-05 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversation',
            old_name='update_at',
            new_name='updated_at',
        ),
    ]
